spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: ${job.name:NONE}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: wvssm827@gmail.com
    password: ejfmngccdvqvpasl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true